### ISSUE TITLE
try half precision ftw

### ISSUE THREAD

**Issue by xraxra** [basujindal/stable-diffusion#1]
figured out that if you call `model.half()` right after `model = instantiate_from_config(config.modelUNet)`
and change `precision = "full"` to `precision = "autocast"` 

it reliably reduces generation time for me (1.82 min to ~1.1) on a 512x512

it might save some memory too and allow larger dimensions 

I compared full precision and half in Beyond Compare, there are some minor differences it detects, but nothing I can notice side by side

**Comment by TingTingin** [comment]
what gpu are you using

**Comment by fastrocket** [comment]
I can confirm the change above reduced my render time, so it's about twice as fast on my RTX 3060.

(Not sure why I can't run the un-optimized Stable Diffusion with the 7GB weights since it runs out of CUDA memory. Maybe Windows 11 4K screen is taking up too much GPU VRAM?)

**Comment by green-s** [comment]
> I can confirm the change above reduced my render time, so it's about twice as fast on my RTX 3060.
> 
> (Not sure why I can't run the un-optimized Stable Diffusion with the 7GB weights since it runs out of CUDA memory. Maybe Windows 11 4K screen is taking up too much GPU VRAM?)

I can't run it on my 3080 either. I've got two 4k monitors but even with one turned off and everything closed (0.6GB allocated) it runs out.

I get a similar speedup to OP with this tweak on the optimized build though.

**Comment by basujindal** [comment]
> figured out that if you call `model.half()` right after `model = instantiate_from_config(config.modelUNet)` and change `precision = "full"` to `precision = "autocast"`
> 
> it reliably reduces generation time for me (1.82 min to ~1.1) on a 512x512
> 
> it might save some memory too and allow larger dimensions
> 
> I compared full precision and half in Beyond Compare, there are some minor differences it detects, but nothing I can notice side by side

You are right; Adding `model.half()` reduces the inference time and required VRAM considerably. I will make the changes arrordingly and push them in a short while. Thank you for the suggestion!

I didn't add it before because, as @green-s said, if I used autocast before calling model.half(), I was getting very little improvement and CUDA OOM for 512X512. Any ideas why we need to add model.half() even when using autocast?

**Comment by xraxra** [comment]
> You are right; Adding `model.half()` reduces the inference time and required VRAM considerably. I will make the changes arrordingly and push them in a short while. Thank you for the suggestion!
> 
> I didn't add it before because, as @green-s said, if I used autocast before calling model.half(), I was getting very little improvement and CUDA OOM for 512X512. Any ideas why we need to add model.half() even when using autocast?

I'm assuming model.half() converts the weights to fp16 & then with autocast used it's allowing for the mix of precisions (if you switch to full it will error about expecting 32bit), but I dont know enough about pytorch
