### ISSUE TITLE
Out of memory.... how big is maximum resolution?

### ISSUE THREAD

**Issue by jnpatrick99** [basujindal/stable-diffusion#11]
I tried 1024x1024 on an RTX 3090, it always crashes (while 768x768 works out). The same thing happens with the original stable repo. How better is this one? What's the maximum res on 24GB? Thanks!

**Comment by basujindal** [comment]
I am not sure since I don't have a 24Gb VRAM GPU. You can gradually increase the resolution in steps of 64 to find out the max res.

**Comment by radoyankov** [comment]
Related, I can't seem to generate a 512x512 one on a 3080 with 10GB memory, with nothing else running. Is 10GB the lower limit, or should I not have a problem with this?
This is the log I'm getting:

> RuntimeError: CUDA out of memory. Tried to allocate 1.50 GiB (GPU 0; 10.00 GiB total capacity; 8.62 GiB already allocated; 0 bytes free; 8.74 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by basujindal** [comment]
This shouldn't be the case. I can run 512x512 using less than 4GB of VRAM. Can you send the command you used to generate images?

**Comment by radoyankov** [comment]
Strange. So it didn't work at all yesterday, but today with the same prompt it did. 
The prompt had everything set at default, just a --prompt.
