### ISSUE TITLE
ModuleNotFoundError: No module named 'optimUtils'  -- From CompVis/stable-diffusion

### ISSUE THREAD

**Issue by nathananderson98** [basujindal/stable-diffusion#112]
From the `README`:
All the modified files are in the [optimizedSD](https://github.com/basujindal/stable-diffusion/blob/main/optimizedSD) folder, so if you have already cloned the original repository you can just download and copy this folder into the original instead of cloning the entire repo.

I started from the main repo, and came here with my 8Gb VRAM card :(

I copied in the optimized `txt2img.py`, which should work with my whole envirnment setup, but my output looks like:

```
Traceback (most recent call last):
  File "scripts/txt2img_optimized.py", line 16, in <module>
    from optimUtils import split_weighted_subprompts, logger
ModuleNotFoundError: No module named 'optimUtils'
```

Googling around I can't find how this module can be installed. Any help with this?
Thanks.

**Comment by DisaKzionda** [comment]
copy file to the same folder where txt2img
![image](https://user-images.githubusercontent.com/53359732/188249477-22385a64-2e42-403c-bb6f-91c8086d6589.png)

**Comment by nathananderson98** [comment]
Yup, could add a note in the Readme if using the base stable diffusion that that file is needed also for the optimized scrpits to run.
