### ISSUE TITLE
Error response from daemon: Unknown runtime specified nvidia - Arch Linux

### ISSUE THREAD

**Issue by hewrym** [basujindal/stable-diffusion#113]
Hi, I'm trying to use Docker on Arch Linux to run this and I'm getting the following error:
```
⠋ Container stable-diffusion-sd-1  Creating                                                                    0.0s
Error response from daemon: Unknown runtime specified nvidia
```

I have installed [docker](https://archlinux.org/packages/community/x86_64/docker/), [docker-compose](https://archlinux.org/packages/community/x86_64/docker-compose/) and [nvidia-container-toolkit](https://aur.archlinux.org/packages/nvidia-container-toolkit) as explained in the readme. I rebooted several times but nothing seems to work.

**Comment by krylm** [comment]
I've just modified docker-compose.yml file and commented out (remove or place # at the line beginning) line with
`#runtime: nvidia`
and it works like a charm!

**Comment by krylm** [comment]
I've modified docker-compose.yml like this and it's fully working with UI interface.

> version: "3.9"
> services:
>   sd:
>     build: .
>     ports:
>       - "7860:7860"
>     volumes:
>       - ../sd-data:/data
>       - ../sd-output:/output
>       - sd-cache:/root/.cache
>     deploy:
>       resources:
>         reservations:
>           devices:
>             - capabilities: [gpu]        
> #runtime: nvidia
> volumes:
>   sd-cache:
>

**Comment by hewrym** [comment]
> I've modified docker-compose.yml like this and it's fully working with UI interface. [docker-compose.yml.txt](https://github.com/basujindal/stable-diffusion/files/9484619/docker-compose.yml.txt)

This solved it, thank you!
