### ISSUE TITLE
Green flat output without `--precision full`

### ISSUE THREAD

**Issue by matteodefelice** [basujindal/stable-diffusion#121]
If I don't set `--precision full`, I get after the computation a plain green image (a constant color). I tried 3-4 different combinations, with and without the full precision. In the latter case, I only got this green output.

**Comment by AxelFar94** [comment]
Is a know issue on GTX 16xx series, need to be fixed on the original CompVis Stable Diffusion fork that this one is based on.

**Comment by basujindal** [comment]
> If I don't set `--precision full`, I get after the computation a plain green image (a constant color). I tried 3-4 different combinations, with and without the full precision. In the latter case, I only got this green output.

Hi, as @AxelFar94 said, it's a know issue with GTX series GPUs. For now, there is no workaround.
