### ISSUE TITLE
Image generation takes longer than 6 minutes on RTX 3050 TI

### ISSUE THREAD

**Issue by 3dfoster** [basujindal/stable-diffusion#149]
I'm able to run the text2img script on my laptop with just 4 GB VRAM which is fantastic, but the time it takes for the "Tesla in the rain" example prompt to generate took over six minutes. I'm wondering if this is expected behavior for only 4GB of RAM or if there are values I can tweak in the command to get the command to run faster. Windows Task Manager shows the GPU running at 97% while the command is running so the graphics card is being fully utilized.

The command:
```
python optimizedSD/optimized_txt2img.py --prompt "Cyberpunk style image of a Telsa car reflection in rain" --H 512 --W 512 --seed 27 --n_iter 2 --n_samples 5 --ddim_steps 50
```

**Comment by eelstork** [comment]
You are generating 2x5 = 10 images; if this takes about 6 minutes it's a good score, and expected behavior.
You can change the number of images output with n_iter and n_samples

**Comment by 3dfoster** [comment]
Thanks for the clarification.
