### ISSUE TITLE
length of prompt

### ISSUE THREAD

**Issue by thezveroboy** [basujindal/stable-diffusion#18]
there are an error on Windows because with long prompt you can't save the result for this path. maybe it will be better to cut the prompt for short path to keep it away from any issue?

Traceback (most recent call last):
File "optimizedSD/optimized_txt2img.py", line 158, in
os.makedirs(sample_path, exist_ok=True)
File "C:\Users\cotton\miniconda3\envs\ldm\lib\os.py", line 223, in makedirs
mkdir(name, mode)
FileNotFoundError: [WinError 3] System can't find the path ...

**Comment by Savager3435** [comment]
You could just manually change they wait it names things. 

img2img is at line 185ish
text2img is at line 150ish

I personally replaced it with this:

> now = datetime.now()
> outputpathname = now.strftime('%H-%M-%S')
> 
> sample_path = os.path.join(outpath, "samples", outputpathname)

simply names the output Hour.Minute.Second, in 24 hour format.
To make that work all you have to do is comment out the previous line:

> sample_path = os.path.join(outpath, "_".join(opt.prompt.split())[:255])

and add:

> from datetime import datetime 

at the top

**Comment by basujindal** [comment]
Have modified the code to slice the path length to the first 255 characters. Please report if the above issue still exists. Thanks!

**Comment by thezveroboy** [comment]
sorry but doesn't work for me because 255 is the full patch from 'C;\Users..' to the last character of prompt. for me it's:

c:\Users\cotton\stable-diffusion\outputs\txt2img-samples\ = 57 chars + 255 chars of prompt = overflow

and you can't know how long the name of user and that's why 255 not so good

so i change in 'optimized_txt2img.py' the line

sample_path = os.path.join(outpath, "_".join(opt.prompt.split())[:255])

to

sample_path = os.path.join(outpath, "_".join(opt.prompt.split())[:100])

and it works fine now

maybe it will be better to work with output folder without any subfolders with names?
