### ISSUE TITLE
Anaconda blocked while installing pip dependencies

### ISSUE THREAD

**Issue by Michoko92** [basujindal/stable-diffusion#19]
Hi,

I spent the whole day trying to figure out why the procedure to install the SD environment didn't work on my Windows 10 machine. Everything was downloading properly, but the process was stuck at "Installing pip dependencies", which lasted forever. After lots of tests, I finally discovered that it was due to a hidden prompt that was not appearing, blocking the whole installation. This prompt happens when the installer tries to download a repo from github: if the folder already exists, pip asks if you want to wipe it or backup it, causing this block (as it is not visible).

Solution: just delete the "src\clip" and "src\taming-transformers" folders before launching the environment creation. I strongly suggest you remove them from the repo, as they are not in the original one. It will save many headaches to people, I guess. Cheers!

**Comment by basujindal** [comment]
Thank you for the suggestion, I have deleted the src folder.
