### ISSUE TITLE
no module named "taming"

### ISSUE THREAD

**Issue by Los-3r** [basujindal/stable-diffusion#202]
Tried to generate an image, but got stopped with this error (shown below)
![image](https://user-images.githubusercontent.com/66935939/193479163-10cf108a-5bae-496d-b988-426aeacc8cad.png)
Any help with this would be much appreciated.

**Comment by BasToTheMax** [comment]
How did you fix it?

**Comment by igorcantele** [comment]
Same error here, anyone had fixed it?
