### ISSUE TITLE
Save/Print seed per sample?

### ISSUE THREAD

**Issue by Caladain** [basujindal/stable-diffusion#23]
I've modified the code to set a random seed in the n_iter loop...and for now have that set as the filename.  This works, but ideally it would instead be triggered off of each sample generated instead of sledgehammered in.
But what I can't figure out is if I wanted to use n_samples...how do I fetch the seed that generated each sample?  I'd like to be able to get not only the image out, but also the seed associated with it so that I can run variations on that seed.

Thanks!

**Comment by basujindal** [comment]
Hi, I am aware of this issue, will try to fix it and push the update today itself. Please feel free to comment if you have any suggestions.

**Comment by jtkelm2** [comment]
A generated txt file with names and seeds would be simplest, I think.

**Comment by basujindal** [comment]
The image name will now contain the seed number that can be used to generate it again. Please report if you find any bugs in the new implementation. Thank you!
