### ISSUE TITLE
No module named LDM found

### ISSUE THREAD

**Issue by matthew-bryce** [basujindal/stable-diffusion#232]
I already have the main branch of stable diffusion up and running on my PC without any problems. I copied the optimizedSD folder to my existing directory and when trying to run the optimized_txt2img I get the "no module named LDM found" error. I am on an M1 Mac with 8gb of ram. Any guidance would be appreciated

**Comment by basujindal** [comment]
Hi, this repo is not compatible with M1. Sorry about that : /

**Comment by matthew-bryce** [comment]
No worries, thanks for the quick response!
