### ISSUE TITLE
img2img problem 

### ISSUE THREAD

**Issue by geowjm** [basujindal/stable-diffusion#25]
loaded input image of size (640, 640) from G:\ejem.jpg
Traceback (most recent call last):
  File "optimizedSD\optimized_img2img.py", line 219, in <module>
    init_image = load_img(opt.init_img, opt.H, opt.W).to(device)
  File "optimizedSD\optimized_img2img.py", line 41, in load_img
    w, h = map(lambda x: x - x % 32, (w0, h0))  # resize to integer multiple of 32
  File "optimizedSD\optimized_img2img.py", line 41, in <lambda>
    w, h = map(lambda x: x - x % 32, (w0, h0))  # resize to integer multiple of 32
TypeError: unsupported operand type(s) for %: 'NoneType' and 'int'

any suggestions? thanks

**Comment by jvvilar** [comment]
I get exactly the same problem. I get past this point with the original img2img, but alas when sampling begins CUDA runs out of memory.

**Comment by basujindal** [comment]
Thank you for reporting the bug; I have fixed it and will push the changes to the repo in a while. Cheers!

**Comment by basujindal** [comment]
Have pushed the changes, please report if the error still exists. Thank you

**Comment by basujindal** [comment]
Just to confirm, did you pass the correct path to the initial image while running the script?

**Comment by feelingok** [comment]
--prompt "prompt" --init-img "C:\stb\stable-diffusion-main\input.jpg" --strength 0.75

This is the prompt I use when I get that message, the location is correct and the image opens normally in my default viewer

**Comment by TingTingin** [comment]
you have to set output size with --H and --W as theres no default set

**Comment by mohammedalsayegh** [comment]
passing fallowing to script:  `python optimizedSD/optimized_img2img.py --prompt "Austrian alps" --init-img sketch-mountains-input.jpg --strength 0.8 --n_iter 2 --n_samples 5 --H 576 --W 768`

It result with fallowing error `AttributeError: 'UNet' object has no attribute 'sqrt_alphas_cumprod'`

<img width="936" alt="image" src="https://user-images.githubusercontent.com/40126750/186290479-ef5b3116-475c-481c-8756-af442963df3a.png">

**Comment by basujindal** [comment]
> passing fallowing to script: `python optimizedSD/optimized_img2img.py --prompt "Austrian alps" --init-img sketch-mountains-input.jpg --strength 0.8 --n_iter 2 --n_samples 5 --H 576 --W 768`
> 
> It result with fallowing error `AttributeError: 'UNet' object has no attribute 'sqrt_alphas_cumprod'`
> 
> <img alt="image" width="936" src="https://user-images.githubusercontent.com/40126750/186290479-ef5b3116-475c-481c-8756-af442963df3a.png">

I cannot reproduce the error. Can you try again with the latest version of this repository?

**Comment by mohammedalsayegh** [comment]
Thank you for the recent repository, it worked as intended!

**Comment by sparta218** [comment]
I am still getting the exact same UNet issue as mohammed, even with the new repo

**Comment by sparta218** [comment]
I figured out the issue, I moved all the files in optimizedSD to scripts and was calling them there, I noticed that the error was referencing the ddpm.py in optimizedSD still, and then I called img2img from optimizedSD and it worked.
