### ISSUE TITLE
Issue with file names and lengthy prompts.

### ISSUE THREAD

**Issue by lessirey** [basujindal/stable-diffusion#27]
The Folder and file names try to include the entire prompt, which is good.. but on lengthy prompts the system breaks and gives an error that file cannot be found since (windows) cant create such a lengthy name. its fine on smaller prompts.

Ideally its good to include the prompt but truncated to specific length and end with seed value.
eg:
[beginning part of the prompt, but truncated]+[addtitional parameters]+[seed value].png

**Comment by basujindal** [comment]
Hi, thank you for reporting the issue; I have truncated the folder name to 150 characters and pushed the changes.
Working on the seed part, will add the seed to the image name once done.

**Comment by lessirey** [comment]
Great. That was fast 👍🏻
Appreciate your work.. i am able to run @1024p on my GTX 2070 without issues

**Comment by basujindal** [comment]
The image name will now contain the seed number that can be used to generate it again. Please report if you find any bugs in the new implementation. Thank you!

**Comment by lessirey** [comment]
Excellent 👍🏻👍🏻
