### ISSUE TITLE
Img2Img 6GB VRAM optimization

### ISSUE THREAD

**Issue by RavetcoFX** [basujindal/stable-diffusion#3]
I tried porting the couple of instances of
```
 mem = torch.cuda.memory_allocated()/1e6
 while(torch.cuda.memory_allocated()/1e6 >= mem):
     time.sleep(1)
```
to img2img.py, but my understanding of the code is limited and it just stays stuck at 0% Sampling and data.
Any Ideas?

**Comment by sawolf** [comment]
If you think about what your snippet of code does, it should:
- check if your GPU-allocated memory is the same as it was previously
- wait until it's not

There's nothing in that code that would reduce the amount of memory allocated, hence you getting stuck in an infinite loop.

To answer your other question, the actual work that the owner of this repo did involves splitting the CompVis model apart and moving the pieces onto and off of the GPU at the right times. I have a repository that's a fair bit closer to working (generates images with noise applied to them - doesn't actually transform them very much)- will send in a PR once I get TortoiseGit working again.

**Comment by RavetcoFX** [comment]
Thanks, I have lots to learn, I was hoping the "wait till it's not" would run the model under max vram alloc

**Comment by sawolf** [comment]
update - see #5 for code & progress so far

**Comment by basujindal** [comment]
Added optimized_img2img.py
