### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by csunberry** [basujindal/stable-diffusion#39]
Hello!

I was having this issue repeatedly:

EDIT: I forgot --prompt on this example; sorry about that!

``(ldm) C:\StableDiffusion\stable-diffusion-main>python "optimizedSD\optimized_txt2img.py" "bubble sheep"
usage: optimized_txt2img.py [-h] [--prompt [PROMPT]] [--outdir [OUTDIR]] [--skip_grid] [--skip_save]
                            [--ddim_steps DDIM_STEPS] [--fixed_code] [--ddim_eta DDIM_ETA] [--n_iter N_ITER] [--H H]
                            [--W W] [--C C] [--f F] [--n_samples N_SAMPLES] [--n_rows N_ROWS] [--scale SCALE]
                            [--from-file FROM_FILE] [--seed SEED] [--small_batch] [--precision {full,autocast}]
optimized_txt2img.py: error: unrecognized arguments: bubble sheep``

(This was happening regardless of height and width. I literally typed something about a banana chasing an ice cream monster and got it.)

So I updated, ran things like I was before, which were working, and I got:

``
(ldm) C:\StableDiffusion\stable-diffusion-main>python "optimizedSD\optimized_txt2img.py" --prompt "bubble sheep"
  File "optimizedSD\optimized_txt2img.py", line 8
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax``

So I just thought I would let you know. :) 

Thank you for all your hard work, and have a lovely day!!

EDIT2: I also want to mention I originally followed Tingting's tutorial, to a degree.

**Comment by forgotPassword** [comment]
Try following this guide: https://old.reddit.com/r/StableDiffusion/comments/wuyu2u/how_do_i_run_stable_diffusion_and_sharing_faqs/

**Comment by csunberry** [comment]
Which part? 

I can actually run the images fine before I updated the SD folder.

Once I did that, though, it came up with the syntax error.

I want to be clear that before I could run it--it would just randomly pop up with that argument.

**Comment by akx** [comment]
You've "updated" your `optimized_txt2img.py` to what appears to be an HTML document, not a Python script.

The original file would have worked fine, but your command was wrong.

Instead of

```
python "optimizedSD\optimized_txt2img.py" "bubble sheep"
```

you need

```
python optimizedSD\optimized_txt2img.py --prompt "bubble sheep"
```
(the `--prompt` being the important bit).

**Comment by csunberry** [comment]
Oh my goodness, I am SO sorry about that! Lmfao!

I totally forgot about that. ADHD man.

But no, I realize my example is from --prompt, but as I mentioned it was either popping up and going away and this was from just removing keywords. However, it seemed to crop up most with height and width, so maybe I am doing something wrong in that department. 

Again, though, I want to reiterate that I was able to generate things, and that this was about the syntax error above. 

As far as the html document, and updating it, I downloaded it directly from Git and I didn't change anything. It is showing in .py file format.

That said, I after I checked line 8, I realized that it might be that I do not have einops.

I went to Anaconda to find the found the phrase, put it in, and it looks like it was NOT downloaded. I installed it. So when I get back later, I will try it, and see if that is the issue, and post exact screenshots, if necessary.

**Comment by csunberry** [comment]
Alright; I figured it out!

It was not the files--they were fine, just as I said.

I went back and checked all the dependencies, went through, and just straight up went through checking them. I installed the diffusers, the invisible-watermark again, etc.  After that, it worked just fine, both with the files I got from the tutorial, and just running Anaconda. 

Thanks!
