### ISSUE TITLE
Need to include an option to not append the prompt in the output path

### ISSUE THREAD

**Issue by wborgo** [basujindal/stable-diffusion#46]
As mencioned in the discussion, when there is a long prompt, it causes windows to truncate the output directory name, causing a FileNotFound exception.
It will be grate to have an option to use the exact output path specified.

### Discussed in https://github.com/basujindal/stable-diffusion/discussions/26

<div type='discussions-op-text'>

<sup>Originally posted by **lessirey** August 23, 2022</sup>
The Folder and file names try to include the entire prompt, which is good.. but on lengthy prompts the system breaks and gives an error that file cannot be found since (windows) cant create such a lengthy name. its fine on smaller prompts.

Ideally its good to include the prompt but truncated to specific length and end with seed value.
eg:
[beginning part of the prompt, but truncated]+[addtitional parameters]+[seed value].png</div>

**Comment by wborgo** [comment]
For now, you can just replace one line in img2img or txt2img:

from
`sample_path = os.path.join(outpath, "_".join(opt.prompt.split()))[:255]`

to
`sample_path = os.path.join(outpath)[:255]`

**Comment by basujindal** [comment]
Hi, yesterday's update changed the max path length from 255 to 150. You can pull the latest version to resolve this issue. Cheers!
