### ISSUE TITLE
Prompt weighting feature

### ISSUE THREAD

**Issue by morganavr** [basujindal/stable-diffusion#50]
Code is already written, it's here:
https://github.com/lstein/stable-diffusion/pull/18

Prompt weighting is a very powerful feature allowing users to make specific changes to already generated image (by using its seed) .
For example, I have a picture of a woman and I want this woman to wear a crown, then I just alter original prompt as "beautiful woman sitting on a chair:1 wearing a crown:0.2" and a crown will appear almost without any modification to original image.

**Comment by basujindal** [comment]
Hi, thank you for the suggestion, I will implement this feature today. Cheers!

**Comment by basujindal** [comment]
Added support for weighted prompts.
