### ISSUE TITLE
AssertionError when running img2img

### ISSUE THREAD

**Issue by sparta218** [basujindal/stable-diffusion#51]
I've been running some img2img prompts all day with no hitch, but a few hours ago I started picking up an AssertionError

Traceback (most recent call last):
File "scripts/optimized_img2img.py", line 220, in
assert os.path.isfile(opt.init_img)
AssertionError

After a while of trying to fix it it began to say that ldm was having syntax errors around some print statements, saying the issue was that parentheses were missing. I tried reinstalling ldm and then it began saying that ldm couldn't be found as a module. I reinstalled the entire env and now I'm back to square one with the AssertionError above.

**Comment by jtkelm2** [comment]
os.path.isfile checks whether such-and-such a file exists. If you say that this problem suddenly appeared after working without a problem, have you quadruple checked that your initialization image's file name is formatted and typed correctly?

**Comment by sparta218** [comment]
Wow, I feel like an idiot. The directory was correct, as was the file name, but the extension wasn't. I spent a good chunk of my evening trying to diagnose this on my own, haha. Think horses, not zebras I suppose. Thanks for your help!
