### ISSUE TITLE
If the number of prompts entered from the argument "--from-file" does not match the number of "--n_samples", an error occurs.

### ISSUE THREAD

**Issue by samia-done** [basujindal/stable-diffusion#55]
Not optimized, but I personally add the code between 211ish and 212ish:

```py
else:
    print(f"reading prompts from {opt.from_file}")
    with open(opt.from_file, "r") as f:
        data = f.read().splitlines()
        data = batch_size * list(data)
        data = list(chunk(data, batch_size))
```

You can then output to the prompt entered from the "-from-file" argument.

I am Japanese.
I use automatic translation.
Please forgive my poor English.

**Comment by basujindal** [comment]
Hi, thank you for the suggestion. I have implemented the suggested edits and pushed the changes. Cheers!

**Comment by samia-done** [comment]
Thank you very much.
