### ISSUE TITLE
Add ETA Scale in Gradio Interface

### ISSUE THREAD

**Issue by htkg** [basujindal/stable-diffusion#59]
Hello! :)

It would be nice to implement ETA scale in the Gradio interface because it is proven to have an high effect on the pictures.
![image](https://user-images.githubusercontent.com/18707625/186705802-54a00936-15f6-4c9a-b797-02d9d2b095e6.png)

**Comment by basujindal** [comment]
Hi, thank you for the suggestion, I have added support for ETA scale in gradio interface and pushed the changes. Cheers!
