### ISSUE TITLE
Optimizing speed

### ISSUE THREAD

**Issue by Michoko92** [basujindal/stable-diffusion#69]
Hi,

As an RTX 2060 user (MSI RTX 2060 Gaming card), I really appreciate the work you put into this repo. Amazing job!

Since I want to generate 512x704 pictures, your repo is the only one that works with 6 GB of VRAM. However, when I generate a 512x512 image for example, I get around an image in 55 seconds (for 50 steps), which seems to be twice the time that is announced in the readme. If I increase the amount of samples, then the time per image is optimized (about 2:30 minutes for 8 images). But when entering an iterative phase where I only fine tune one image, it can get pretty slow.

When I monitor the used VRAM, I see that for 512x704 images, only about 4.5 GB are used. In the readme, it is stated that the model is split into 4 pieces, that are uploaded when required. So I was wondering: for people having 6 GB of VRAM, do you think that only splitting the model in 2 parts would be faster? Also, do you think that having the script running and keeping the model in CPU RAM between prompts would make initialization faster?

Thank you so much!

Edit: I'm realizing that the WebUI is already doing my second suggestion of keeping the script running without loading the model off the disk each time, right?

**Comment by basujindal** [comment]
Hi, thank you for the suggestion. You are right, the WebUI keeps the model loaded in the CPU for faster inference.
I will try splitting the model into three parts instead of four. Going from 3 to 4 parts increases the inference time considerably but saves around 1GB of VRAM. I am considering adding an option to use only 3 parts which should save a lot of time at the expense of VRAM. Will try to do it today itself. Cheers!

**Comment by basujindal** [comment]
Hi, I have added an optional argument `--turbo`. Using it will reduce the inference time to 25 sec per image for txt2img and 15sec per image for img2img (excluding the time to load the model once) at the expense of around 1GB VRAM.

**Comment by Michoko92** [comment]
Man, this is absolutely amazing!!

I did some tests, and I can't believe my eyes: I can generate a 512x704 image in 22 seconds, and a 512x768 (!) image in 24 seconds! And all this on my good old RTX 2060. You are doing miracles, my friend!

I did a quick comparison with Waifu + hlky UI (the one I was using until now) and the speed is the same in 512x512 (but waifu can't go higher in resolution, so I can't compare them). Even a Google colab with a T4 GPU gives me more or less this speed for a 512x704 image. So this is absolutely fantastic!

This is definitely a wonderful achievement, congratulations. Now I really wish there was a way to merge the great additions hlky brought to SD (other samplers, gfpgan, mask painting, to name a few) with your optimizations. Did you check his repo here: https://github.com/hlky/stable-diffusion-webui ? Pretty awesome stuff too. I saw that he put your optimizedSD scripts on his main SD repo (here https://github.com/hlky/stable-diffusion), so maybe a merge of all improvements is considered? I think it may not be necessary to reinvent the wheel, and develop several UIs separately IMHO.

Anyway, thank you again so much for this awesome addition, and I can't wait to see what you will do next. Cheers! :)

**Comment by TheEnhas** [comment]
Big difference now, it even works on my 3060 Ti when generating big batches of images but the effect is much less (20 512x512 50 step images is just over 4 minutes for me without turbo, about 3:40 with it on). With single images, however, I went from about a minute for one 512x512 50 step image to 13 seconds. If you can afford the VRAM hit it's best to have it on no matter how much you're generating, IMO.

**Comment by Michoko92** [comment]
I think that since it works faster on small batches, it might be interesting to use "n_iter" instead of "n_samples" if you want to create multiple images. In other words, multiple small batches instead of a big one.

**Comment by ryudrigo** [comment]
Just to contribute with some numbers regarding n_iter and n_samples:

n_iter 4
n_samples 1
unet_bs 1
ddim_steps 100
turbo enabled
size 512 512
time 1min 13 sec

n_iter 1
n_samples 4
unet_bs 8
ddim_steps 100
turbo enabled
size 512 512
time 57 sec

So, if you have the RAM, it's better to run it with a large n_samples AS LONG AS you also increase unet_bs to 2xnum_samples

If incresing unet_bs so much seems out of question, try pull request #117 with the chunking modification (see my comment there)

Increasing unet_bs to 8 and batch_size to 4 (in experiments above) consumed 8.1GB of my 3060 card.
