### ISSUE TITLE
optimized_txt2img --from-file does not create correct output directories

### ISSUE THREAD

**Issue by MrLagSux** [basujindal/stable-diffusion#71]
Using `python optimizedSD\optimized_txt2img.py --from-file optimizedSD/prompts.txt --H 512 --W 512 --n_iter 1 --n_samples 5 --ddim_steps 50 --precision full` I would expect there to be an output folder named after every prompt.
Instead I get a folder called `a_painting_of_a_virus_monster_playing_guitar` and all generated images are put in there.

**Comment by basujindal** [comment]
> Using `python optimizedSD\optimized_txt2img.py --from-file optimizedSD/prompts.txt --H 512 --W 512 --n_iter 1 --n_samples 5 --ddim_steps 50 --precision full` I would expect there to be an output folder named after every prompt. Instead I get a folder called `a_painting_of_a_virus_monster_playing_guitar` and all generated images are put in there.

Hi, thank you for reporting the bug, I have fixed it and pushed the changes. Cheers!
