### ISSUE TITLE
Optimized img2img error :(

### ISSUE THREAD

**Issue by shade1er** [basujindal/stable-diffusion#72]
Impossible to run img2img.
everything else is fine and working good...

`in module init_latent ... object has no attribute '{}'".format( AttributeError: 'FirstStage' object has no attribute 'get_first_stage_encoding'`

any ideas ? thanks !

**Comment by basujindal** [comment]
Hi, can you once try pulling the latest version of the repo and trying again?

**Comment by shade1er** [comment]
Same error after pulling the latest version : 

```
File "/home/shade/sd14/./optimizedSD/img2img_gradio.py", line 128, in generate
    init_latent = modelFS.get_first_stage_encoding(modelFS.encode_first_stage(init_image))  # move to latent space
  File "/home/shade/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'FirstStage' object has no attribute 'get_first_stage_encoding'
```

**Comment by shade1er** [comment]
i have erased ldm conda env, created it again, then updated pytorch torchvision...
and it works. i don't know what went wrong at the 1st install.
thank you very much
