### ISSUE TITLE
AttributeError: 'UNet' object has no attribute 'ddim_timesteps'

### ISSUE THREAD

**Issue by art926** [basujindal/stable-diffusion#98]
When I run  optimizedSD/optimized_txt2img.py  with --sampler ddim, I'm getting this error:
AttributeError: 'UNet' object has no attribute 'ddim_timesteps'
I think all my files are up to date.

**Comment by slack-t** [comment]
Having the same issue when trying to use the DDIM sampler...

**Comment by basujindal** [comment]
Thank you for reporting the error; I have fixed the bug and will push the changes in 10 minutes. Thanks!

**Comment by basujindal** [comment]
Hi, I have pushed the required changes; please inform if the error still exists. Thanks!

**Comment by slack-t** [comment]
Hi @basujindal 

It works perfectly fine now! Thank you so much!
